"""Task-oriented context retrieval contracts."""

from monas_lens.retrieval.bundle import ContextBundleBuilder
from monas_lens.retrieval.compiler import ContextCompiler
from monas_lens.retrieval.confidence import (
    CONFIDENCE_COMPONENT_WEIGHTS,
    CONFIDENCE_FORMULA_VERSION,
    EVIDENCE_AGREEMENT_TABLE,
    PRIMARY_CERTAINTY_TABLE,
    PRIMARY_CERTAINTY_TABLE_VERSION,
    ConfidenceAssessment,
    ConfidenceGate,
    ConfidenceGateOutcome,
    ConfidenceWidenerProtocol,
    assess_confidence,
)
from monas_lens.retrieval.contracts import (
    CONTEXT_SCHEMA_VERSION,
    CandidateRole,
    ConfidenceComponents,
    ConfidenceReason,
    ConfidenceResult,
    ConfidenceStatus,
    ContextBudget,
    ContextBundle,
    ContextSnippet,
    ContextSourceReference,
    DiagnosticSeverity,
    EntityType,
    EvidenceKind,
    RankedCandidate,
    RetrievalCandidate,
    RetrievalDiagnostic,
    RetrievalDiagnosticCode,
    RetrievalEvidence,
    RoleTokenUsage,
    ScoreComponents,
    TaskAction,
    TaskContextRequest,
    TaskResolution,
    TokenEstimate,
    ValidationCommand,
    parse_task_context_request,
)
from monas_lens.retrieval.ranker import deduplicate_candidates, rank_candidates
from monas_lens.retrieval.resolver import resolve_task
from monas_lens.retrieval.retriever import (
    GitDiffAdapterProtocol,
    GitDiffHunk,
    GitDiffResult,
    GraphAdapterProtocol,
    GraphServiceAdapter,
    IndexedChunk,
    IndexedChunkLookupAdapter,
    IndexedChunkLookupProtocol,
    ParallelRetriever,
    RetrievalBatch,
    RetrievalExpansion,
    SearchAdapterProtocol,
    SearchServiceAdapter,
    SubprocessGitDiffAdapter,
)
from monas_lens.retrieval.token_estimator import (
    HeuristicTokenEstimator,
    TokenEstimatorProtocol,
    allocate_budget,
    create_default_estimator,
    crop_text_to_budget,
)
from monas_lens.retrieval.validation import suggest_validation_commands

__all__ = [
    "CONFIDENCE_COMPONENT_WEIGHTS",
    "CONFIDENCE_FORMULA_VERSION",
    "CONTEXT_SCHEMA_VERSION",
    "EVIDENCE_AGREEMENT_TABLE",
    "PRIMARY_CERTAINTY_TABLE",
    "PRIMARY_CERTAINTY_TABLE_VERSION",
    "CandidateRole",
    "ConfidenceAssessment",
    "ConfidenceComponents",
    "ConfidenceGate",
    "ConfidenceGateOutcome",
    "ConfidenceReason",
    "ConfidenceResult",
    "ConfidenceStatus",
    "ConfidenceWidenerProtocol",
    "ContextBudget",
    "ContextBundle",
    "ContextBundleBuilder",
    "ContextCompiler",
    "ContextSnippet",
    "ContextSourceReference",
    "DiagnosticSeverity",
    "EntityType",
    "EvidenceKind",
    "GitDiffAdapterProtocol",
    "GitDiffHunk",
    "GitDiffResult",
    "GraphAdapterProtocol",
    "GraphServiceAdapter",
    "HeuristicTokenEstimator",
    "IndexedChunk",
    "IndexedChunkLookupAdapter",
    "IndexedChunkLookupProtocol",
    "ParallelRetriever",
    "RankedCandidate",
    "RetrievalBatch",
    "RetrievalCandidate",
    "RetrievalDiagnostic",
    "RetrievalDiagnosticCode",
    "RetrievalEvidence",
    "RetrievalExpansion",
    "RoleTokenUsage",
    "ScoreComponents",
    "SearchAdapterProtocol",
    "SearchServiceAdapter",
    "SubprocessGitDiffAdapter",
    "TaskAction",
    "TaskContextRequest",
    "TaskResolution",
    "TokenEstimate",
    "TokenEstimatorProtocol",
    "ValidationCommand",
    "allocate_budget",
    "assess_confidence",
    "create_default_estimator",
    "crop_text_to_budget",
    "deduplicate_candidates",
    "parse_task_context_request",
    "rank_candidates",
    "resolve_task",
    "suggest_validation_commands",
]
